# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-14 21:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city_issues', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locationX', models.FloatField()),
                ('locationY', models.FloatField()),
                ('description', models.CharField(max_length=128)),
            ],
        ),
    ]
